name: ezetcd
version: 0.1.0
author: Name It Later
description: A client for etcd
homepage: https://github.com/nameitlater/ezetcd
environment:
  sdk: '>=1.4.3 <2.0.0'
dependencies:
  intl: '>=0.9.10 <0.10.0'
  logging: '>=0.9.0 <0.10.0'
dev_dependencies:
  unittest: '>=0.11.0 <0.12.0'
  scheduled_test: '>=0.11.0 <0.12.0'

